language: node_js
node_js:
- '10'
sudo: true
branches:
  only:
  - master
before_install:
- npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
- npm i -g npm@^6.14.4
install:
- npm ci
- true
cache:
  directories:
  - "$HOME/.npm"
env:
  global:
  - secure: hu5cpsMinQEpoNgnJv1XQ+509/57gM4dHg+mRXaAkZ7ha6k0AK1AmNgsCKYfs2G8Qe3eFGM3DTuJA0JV9vOcUeHNURGQKW+ukciSN1dT8dmLC6DAjgd89LIV5jsgAMBtNNCeIDwdpSEhe39nD4P1ligVpxxtY9kbOfK+F/cNbgj9ZpC/MZ55rniMa1JkZpfWwP3bdOcko56E+dB3/Dh8L0QF1hiDA1AwpGXQcO2jQ22HvTyUIezcgIYGGSUJ0N9gPhe7f0UQ4iCdMbq2rKv2wi4vzKQPFOkK8eYAUfhbv1iHy/bP2VX8tR7ac9XJuAznaHJ3tng8iEnvF5ForiaAVhtUNOUi1Hw0i2qdaoash0hJh3Aq8IwyFZiZYAQYmIC29VuoPQJgTPVECEDkzqs8fbC0nqwjG9aVP6OkGUgSmR9LChUVsF8ZfLAp/R4bY0XJh6vuqG00qfl90f2zooTA/HPQa7D2VJBEDretZLR0u1ufPHEPkl++o5MeaeNn98KYKOD66fqK+lHf1fmyBogRRefXFZFOi1zNgZTe+xA6nNHk9eAMvYf9CfIsRM7AVnBviTWBkx3S5KDcbof8rdyUymwu5T/7Hly6JZmYKLZ5esQHoV2J5LYOxeaZoXXLARgQkxdpf/9sxNVkkB8TW6llnk+Bd7o7Qn9to80m60X2zsQ=
  - secure: "nHD48tYG5jDsFdgE5h7ZLxEYmIeXmjlcB+lswQqTzBOAgPSPmf89OCH1AYXQz2Bf9DhynIspPIQxuM/peeaPNLiuvBKubVtmSTMLrM3dyy2x9XUUKnGDEQPS0lOWA6k/Nyx2k4tqyx8Jvlzfgy3ayWyQQOxm8Rfmn4oyNz4ePCOxKwVIaeNwvdLzg5MqU9oDgxsSL2CGuHRJ7zgyDxxm7rKQcNgFEifUtB3+U0t5WfElWvhyAkgzhTZlfcHhEPqnoDxuQmlHMFl5f6PSvJXSaWaF+Q+co5Apw1KKJOAhfT6e3Pe1dsxTrQzFzzJCKPbjoHfknUBmX4wV0YDTz5VsR/L4L4PqVlZgP8Y8MdbeBwqfZY624wa/x3V4kOtfucEJDVO/n8rAqm3SREdSTN6HwgV6mdr870PUZhG512ZMT7J9IfyeigtQt6OYYDWtCqMb4rYNDsZQeepzWKegdKCByuyxchJZ+1/yg30ql+qeYkdVWV8npjEFU10PGgpo1m21Sqjq6mfjMi7IWT+DSh0oFPj7ua6A/5VTw/5OjqrBHbFmRcCM2cKvuS5dyTG0ETdBDfstgdqINiwW1cYzq9yqu+KDwwOFbeiELAZoQVERDYPu1RbX6ccIi4bYbd09nknxAAcGl1XEegEKouQxBDb6XexOdDnbtaxTFMUa9BsAZyI="
  - OWNER=streamr
  - IMAGE_NAME=network-explorer
import:
 - source: streamr-dev/travis-ci:aws-staging-secrets.yml@master
 - source: streamr-dev/travis-ci:aws-production-secrets.yml@master
 - source: streamr-dev/travis-ci:npm-secrets.yml@master
 - source: streamr-dev/travis-ci:docker-secrets.yml@master
jobs:
  include:
  - stage: Build Docker (dev)
    if: branch = master
    env:
      - TAG=dev
    install: true
    script:
      - docker build -t $OWNER/$IMAGE_NAME:local --build-arg NPM_TOKEN=${NPM_TOKEN} .
      - sudo sysctl fs.inotify.max_user_watches=524288
      - sudo sysctl fs.inotify.max_queued_events=524288
      - sudo sysctl -p
      - travis_scripts/smoke-test.sh
    after_failure:
      - docker ps
      - docker logs network-explorer
    deploy:
      - provider: script
        skip_cleanup: true
        script: bash travis_scripts/deploy-docker.sh dev
        on:
          branch: master
